import { Product } from "@/types/Product";

export const productsMock: Product[] = [
  {
    id: "1",
    name: "Cuenta Digital Plus",
    type: "Cuenta corriente",
    category: "Cuentas",
    description:
      "Cuenta digital sin comisiones con tarjeta de débito gratuita y reintegro de hasta el 2% en compras seleccionadas.",
    interestRate: 0.5,
    minimumAmount: 0,
    benefits: [
      "Sin comisiones de mantenimiento",
      "Tarjeta de débito sin costo",
      "Reintegro del 2% en compras seleccionadas",
      "Transferencias gratuitas ilimitadas",
      "Acceso a la app móvil y banca en línea",
    ],
  },
  {
    id: "2",
    name: "Cuenta de Ahorro Premium",
    type: "Cuenta de ahorro",
    category: "Cuentas",
    description:
      "Cuenta de ahorro con alta rentabilidad y liquidez inmediata. Ideal para hacer crecer tu dinero sin renunciar a la disponibilidad.",
    interestRate: 3.2,
    minimumAmount: 1000,
    benefits: [
      "Alta rentabilidad mensual",
      "Liquidez inmediata",
      "Sin comisiones por retiros",
      "Depósitos programados automáticos",
      "Alertas de movimientos por email y SMS",
    ],
  },
  {
    id: "3",
    name: "Tarjeta Platinum Rewards",
    type: "Tarjeta de crédito",
    category: "Tarjetas",
    description:
      "Tarjeta de crédito premium con programa de recompensas exclusivo y beneficios de viaje. Acumula puntos por cada compra y canjéalos por viajes, productos o experiencias.",
    interestRate: 18.9,
    benefits: [
      "Acumulación de 2 puntos por cada $1 gastado",
      "Seguro de viaje internacional",
      "Acceso a salas VIP en aeropuertos",
      "Descuentos en restaurantes seleccionados",
      "Protección de compras y garantía extendida",
    ],
  },
  {
    id: "4",
    name: "Tarjeta Business Pro",
    type: "Tarjeta de crédito empresarial",
    category: "Tarjetas",
    description:
      "Tarjeta diseñada para empresas con beneficios específicos para gastos corporativos y gestión financiera eficiente.",
    interestRate: 16.5,
    benefits: [
      "Reportes detallados de gastos por categoría",
      "Integración con software contable",
      "Tarjetas adicionales con límites personalizados",
      "Descuentos en servicios empresariales",
      "Asistencia prioritaria 24/7",
    ],
  },
  {
    id: "5",
    name: "Préstamo Personal Flexible",
    type: "Préstamo personal",
    category: "Préstamos",
    description:
      "Préstamo personal con condiciones flexibles y rápida aprobación. Ideal para consolidar deudas o financiar proyectos personales.",
    interestRate: 9.8,
    minimumAmount: 5000,
    term: "12 a 60 meses",
    benefits: [
      "Aprobación en 24 horas",
      "Sin penalización por pago anticipado",
      "Cuotas fijas mensuales",
      "Posibilidad de saltar una cuota al año",
      "Seguro de desempleo incluido",
    ],
  },
  {
    id: "6",
    name: "Préstamo Hipotecario Smart",
    type: "Préstamo hipotecario",
    category: "Préstamos",
    description:
      "Financiamiento para la compra de vivienda con tasas competitivas y plazos extendidos. Incluye asesoría personalizada durante todo el proceso.",
    interestRate: 5.2,
    minimumAmount: 50000,
    term: "Hasta 30 años",
    benefits: [
      "Financiamiento de hasta el 80% del valor de la propiedad",
      "Tasas fijas y variables disponibles",
      "Asesoría inmobiliaria gratuita",
      "Reducción de tasa por domiciliación de nómina",
      "Posibilidad de carencia inicial",
    ],
  },
  {
    id: "7",
    name: "Fondo de Inversión Equilibrado",
    type: "Fondo de inversión",
    category: "Inversiones",
    description:
      "Fondo diversificado con balance entre renta fija y variable para un perfil de riesgo moderado.",
    riskLevel: 3,
    minimumAmount: 5000,
    performanceData: [
      { date: "2023-01-01", value: 100 },
      { date: "2023-02-01", value: 102 },
      { date: "2023-03-01", value: 103.5 },
      { date: "2023-04-01", value: 101.8 },
      { date: "2023-05-01", value: 104.2 },
      { date: "2023-06-01", value: 106.7 },
      { date: "2023-07-01", value: 105.9 },
      { date: "2023-08-01", value: 108.3 },
      { date: "2023-09-01", value: 110.1 },
      { date: "2023-10-01", value: 109.4 },
      { date: "2023-11-01", value: 112.6 },
      { date: "2023-12-01", value: 115.2 },
    ],
    benefits: [
      "Diversificación automática",
      "Gestión profesional",
      "Informes trimestrales detallados",
      "Rebalanceo periódico de la cartera",
      "Acceso a mercados internacionales",
    ],
  },
  {
    id: "8",
    name: "Fondo de Renta Variable Global",
    type: "Fondo de inversión",
    category: "Inversiones",
    description:
      "Fondo de inversión enfocado en acciones globales con potencial de crecimiento a largo plazo.",
    riskLevel: 4,
    minimumAmount: 10000,
    performanceData: [
      { date: "2023-01-01", value: 100 },
      { date: "2023-02-01", value: 98.5 },
      { date: "2023-03-01", value: 104.2 },
      { date: "2023-04-01", value: 107.8 },
      { date: "2023-05-01", value: 105.3 },
      { date: "2023-06-01", value: 110.7 },
      { date: "2023-07-01", value: 115.9 },
      { date: "2023-08-01", value: 113.3 },
      { date: "2023-09-01", value: 118.1 },
      { date: "2023-10-01", value: 116.4 },
      { date: "2023-11-01", value: 122.6 },
      { date: "2023-12-01", value: 128.2 },
    ],
    benefits: [
      "Exposición a empresas líderes globales",
      "Potencial de crecimiento a largo plazo",
      "Diversificación geográfica",
      "Gestión activa por expertos en mercados internacionales",
      "Informes mensuales de rendimiento",
    ],
  },
  {
    id: "9",
    name: "Plan de Pensiones Tranquilidad",
    type: "Plan de pensiones",
    category: "Inversiones",
    description:
      "Plan de pensiones con enfoque conservador diseñado para asegurar un retiro tranquilo con crecimiento estable.",
    riskLevel: 2,
    minimumAmount: 1000,
    performanceData: [
      { date: "2023-01-01", value: 100 },
      { date: "2023-02-01", value: 100.8 },
      { date: "2023-03-01", value: 101.5 },
      { date: "2023-04-01", value: 102.1 },
      { date: "2023-05-01", value: 101.9 },
      { date: "2023-06-01", value: 102.7 },
      { date: "2023-07-01", value: 103.5 },
      { date: "2023-08-01", value: 104.2 },
      { date: "2023-09-01", value: 104.8 },
      { date: "2023-10-01", value: 105.3 },
      { date: "2023-11-01", value: 106.1 },
      { date: "2023-12-01", value: 107.2 },
    ],
    benefits: [
      "Crecimiento estable y predecible",
      "Bajo riesgo de inversión",
      "Ventajas fiscales",
      "Aportaciones flexibles",
      "Planificación personalizada para la jubilación",
    ],
  },
  {
    id: "10",
    name: "Seguro de Vida Integral",
    type: "Seguro de vida",
    category: "Seguros",
    description:
      "Seguro de vida completo que protege a tu familia y puede funcionar como instrumento de ahorro a largo plazo.",
    minimumAmount: 100,
    term: "Renovable anualmente",
    benefits: [
      "Cobertura por fallecimiento e invalidez",
      "Componente de ahorro con rentabilidad garantizada",
      "Indemnización por enfermedades graves",
      "Asistencia familiar",
      "Flexibilidad para aumentar coberturas",
    ],
  },
  {
    id: "11",
    name: "Seguro de Salud Premium",
    type: "Seguro de salud",
    category: "Seguros",
    description:
      "Seguro médico completo con amplia cobertura nacional e internacional y acceso a los mejores especialistas.",
    minimumAmount: 80,
    term: "Renovable anualmente",
    benefits: [
      "Cobertura hospitalaria 100%",
      "Red de médicos especialistas",
      "Cobertura internacional en viajes",
      "Telemedicina 24/7",
      "Programas de prevención y bienestar",
    ],
  },
  {
    id: "12",
    name: "Depósito a Plazo Fijo Premium",
    type: "Depósito a plazo",
    category: "Inversiones",
    description:
      "Depósito a plazo fijo con alta rentabilidad garantizada y flexibilidad en los plazos de inversión.",
    interestRate: 4.5,
    riskLevel: 1,
    minimumAmount: 10000,
    term: "3 a 36 meses",
    benefits: [
      "Rentabilidad garantizada",
      "Capital 100% garantizado",
      "Plazos flexibles",
      "Renovación automática opcional",
      "Posibilidad de cancelación anticipada",
    ],
  },
];
